/*
 * generated by Xtext
 */
package io.mapzone.ui.contentassist

import io.mapzone.ui.contentassist.AbstractGeoJSONProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class GeoJSONProposalProvider extends AbstractGeoJSONProposalProvider {
}
