/*
 * generated by Xtext
 */
package io.mapzone.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GeoJSONUiModule extends io.mapzone.ui.AbstractGeoJSONUiModule {
	public GeoJSONUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
