/*
 * generated by Xtext
 */
package io.mapzone;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GeoJSONRuntimeModule extends io.mapzone.AbstractGeoJSONRuntimeModule {

}
