/*
 * generated by Xtext
 */
package io.mapzone;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GeoJSONStandaloneSetup extends GeoJSONStandaloneSetupGenerated{

	public static void doSetup() {
		new GeoJSONStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

